openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker app
  description: This is a documentation of Water Tracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://water-tracker-backend-101-team-5.onrender.com
  - url: http://localhost:8080
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Water
    description: Water intake operations.
paths:
  /water/delete:
    delete:
      $ref: ../swagger/path/water/{id}/delete.yaml
  /water/update:
    patch:
      $ref: ../swagger/path/water/{id}/patch.yaml
  /users/daily-norma:
    post:
      $ref: ../swagger/path/water/dailyPost.yaml
  /water/add:
    post:
      $ref: ../swagger/path/water/addPost.yaml
  /water/day:
    get:
      $ref: ../swagger/path/water/get.yaml
  /water/month:
    post:
      $ref: ../swagger/path/water/monthly.yaml
  /auth/register:
    post:
      $ref: '../swagger/path/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/path/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/path/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/path/auth/refresh.yaml'
  /users/avatar:
    patch:
      $ref: '../swagger/path/auth/avatar.yaml'
  /users/profile:
    get:
      $ref: '../swagger/path/auth/getUser.yaml'
  /users/update:
    patch:
      $ref: '../swagger/path/auth/updateUser.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/path/auth/send-reset-email.yaml'
  /auth/reset-password:
    post:
      $ref: '../swagger/path/auth/reset-pwd.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/path/auth/get-google-oauth.yaml'
  /auth/confirm-oauth:
    post:
      $ref: '../swagger/path/auth/confirm-google-oauth.yaml'
#
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
#
