openapi: 3.1.0
info:
  version: 1.0.0
  title: Water tracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Water
    description: Operations with user watertaking
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:8080
  - url: https://example.com/api/v1
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
