openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker app
  description: This is a documentation of Water Tracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://water-tracker-backend-101-team-5.onrender.com
  - url: http://localhost:8080
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Water
    description: Water intake operations.
paths:
  /water/delete:
    delete:
      $ref: ../swagger/path/water/{id}/delete.yaml
  /water/update:
    patch:
      $ref: ../swagger/path/water/{id}/patch.yaml
  /users/daily-norma:
    post:
      $ref: ../swagger/path/water/dailyPost.yaml
  /water/add:
    post:
      $ref: ../swagger/path/water/addPost.yaml
  /water/day:
    get:
      $ref: ../swagger/path/water/get.yaml
  /water/month:
    post:
      $ref: ../swagger/path/water/monthly.yaml
  /auth/register:
    post:
      $ref: '../swagger/path/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/path/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/path/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/path/auth/refresh.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/path/auth/send-reset-email.yaml'
  /auth/reset-password:
    post:
      $ref: '../swagger/path/auth/reset-pwd.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/path/auth/get-google-oauth.yaml'
  /auth/confirm-oauth:
    post:
      $ref: '../swagger/path/auth/confirm-google-oauth.yaml'
  /users/avatar:
    patch:
      $ref: '../swagger/path/users/avatar.yaml'
  /users/profile:
    get:
      $ref: '../swagger/path/users/getProfile.yaml'
  /users/update:
    patch:
      $ref: '../swagger/path/users/updateProfile.yaml'
components:
  schemas:
    User:
      type: object
      properties:
        userName:
          type: string
          example: 'User'
        dailyNorma:
          type: number
          example: 1500
        email:
          type: string
          example: 'user@example.com'
        gender:
          type: string
          enum: ['Man', 'Woman']
        photo:
          type: string
          example: 'http://example.com/photo.jpg'
    Water:
      type: object
      properties:
        _id:
          description: 'Water id'
          type: string
          example: 66c4b8bd4719066469ce2d02
        userId:
          description: "User's id"
          type: string
          example: 66c4b8bd4719066469ce2d02
        amount:
          description: 'Amount of water'
          type: number
          example: 1500
        time:
          description: 'Time of add water'
          type: string
          example: '11:35'
        date:
          description: 'Date of add water'
          type: string
          example: '2024-09-01'
    monthlyWater:
      type: object
      properties:
        date:
          description: 'Date'
          type: string
          example: '2, September'
        totalAmount:
          description: 'Total amount of water intake per day (ml)'
          type: number
          example: 1200
        servings:
          description: 'Total amount of servings water per day'
          type: number
          example: 5
        dailyNorma:
          description: 'Daily water intake norma selected by the user'
          type: number
          example: 1500
        fullfilment:
          description: 'Percentage of daily water'
          type: number
          example: 50
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
